# Generated by Django 3.0.2 on 2020-01-05 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsappwrap', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='instance',
            name='is_loggedin',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
