# Generated by Django 3.0.2 on 2020-01-14 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsappwrap', '0002_instance_is_loggedin'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebhookUrl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=255)),
            ],
        ),
    ]
